### ISSUE TITLE
On hub.getdbt.com you've got an error in arguments of generate_model_yaml (model_names not model_name)

### ISSUE THREAD

**Issue by elycenok-wowcorp** [dbt-labs/dbt-codegen#176]
### Describe the bug
see issue header

### Steps to reproduce
so I tried to run the very first command example (no matter if it was from the wrong macro description) and it failed

dbt --quiet run-operation generate_model_yaml --args '{"model_name": "stg_jaffle_shop__orders"}' > models/staging/jaffle_shop/stg_jaffle_shop__orders.yml

from here https://hub.getdbt.com/dbt-labs/codegen/latest/

(something like model_name is the wrong parameter of macro generate_model_yaml

**Comment by elycenok-wowcorp** [comment]
To add 

This is the first line I tried 
```
dbt --quiet run-operation generate_model_yaml --args '{"model_name": "stg_jaffle_shop__orders"}' > models/staging/jaffle_shop/stg_jaffle_shop__orders.yml
```

from 
https://hub.getdbt.com/dbt-labs/codegen/latest/

and I was going to give up and abandon this dbt package

**Comment by dbeatty10** [comment]
Thank you for reporting this @elycenok-wowcorp !

This was fixed by https://github.com/dbt-labs/dbt-codegen/pull/164/commits/390ab08ee94c0096178820d7f6c0ac9bc7636455 as part of #164, and the fix will show up at https://hub.getdbt.com/dbt-labs/codegen/latest/ upon the next release (which is coming soon).
