### ISSUE TITLE
[chore] fix integration tests

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-codegen#184]
### Describe the bug

via #174, https://github.com/dbt-labs/dbt-adapters/issues/178 was discovered to bork the integration tests from running.

[CircleCI run](https://app.circleci.com/pipelines/github/dbt-labs/dbt-codegen/403/workflows/533b1150-fbaf-4f8b-82ff-d2be6ebc4d90/jobs/389?invite=true#step-106-2535_91) that fails on the compilation part during execution of of `dbt --warn-error seed --target redshift --full-refresh`

**Comment by emmyoop** [comment]
Just an FYI that I'm in the process of getting thsi working with tox + GH to eventually move away from CircleCI - https://github.com/dbt-labs/dbt-codegen/issues/183

**Comment by dbeatty10** [comment]
### Potential root cause

This might have the same root cause as was discovered in dbt-utils within https://github.com/dbt-labs/dbt-utils/pull/792#issuecomment-2192318186:

> ... the _default_ behavior in Redshift is to lowercase all column names _even if_ a table is created with quoted mixed-case column names.

### Potential solution

This approach worked in dbt-utils as reported in https://github.com/dbt-labs/dbt-utils/pull/792#pullrequestreview-2173083918 on 2024 July 11:

> The tests in Redshift are passing after setting [`enable_case_sensitive_identifier` to `true`](https://docs.aws.amazon.com/redshift/latest/dg/r_enable_case_sensitive_identifier.html#w265aac71c45b7) in the [cluster’s parameter group](https://docs.aws.amazon.com/redshift/latest/mgmt/managing-parameter-groups-console.html#parameter-group-modify) via the [Amazon Redshift console](https://docs.aws.amazon.com/redshift/latest/mgmt/managing-parameter-groups-console.html#parameter-group-modify).

### Proposed next step

I believe dbt-utils and dbt-codegen share the same Redshift cluster, so it might be as simple as re-instating the tests removed in https://github.com/dbt-labs/dbt-codegen/pull/174 on 2024 June 4 and re-running this integration test 🤞
