### ISSUE TITLE
Support preserving capitalisation for models and columns

### ISSUE THREAD

**Issue by Thrasi** [dbt-labs/dbt-codegen#188]
### Describe the feature
generate_model_yaml.sql lower cases every model and column name.
add support for preserving capitalisation.

### Describe alternatives you've considered
Add two optional parameter to the macro, one for model names and one for column names to control the behaviour.

### Who will this benefit?
Anyone working with a database with a naming standard where capitalisation is important.  This is related to the [issue related to generate_source_yaml](https://github.com/dbt-labs/dbt-codegen/issues/140).

### Are you interested in contributing this feature?
Yes, I have what I believe is a working solution to the issue.

**Comment by dbeatty10** [comment]
Thanks for reaching out @Thrasi !

This looks like the same/similar thing as requested in https://github.com/dbt-labs/dbt-codegen/issues/175, so I'm going to close this one as a duplicate.

Would welcome any additional thoughts you have over there. Since you closed your draft PR, would also be interested to learn if you came up with a workaround.
