### ISSUE TITLE
generate_model_yaml + windows

### ISSUE THREAD

**Issue by jakub-auger** [dbt-labs/dbt-codegen#37]
the generate_model_yaml command example doesn't work on windows

```
DBT>dbt run-operation generate_model_yaml --args '{"model_name": "customers"}'
usage: dbt [-h] [--version] [-r RECORD_TIMING_INFO] [-d]
           [--log-format {text,json,default}] [--no-write-json]
           [--use-colors | --no-use-colors] [-S] [--warn-error]
           [--partial-parse | --no-partial-parse]
           {docs,source,init,clean,debug,deps,list,ls,snapshot,rpc,run,compile,parse,test,seed,run-operation}
           ...
dbt: error: unrecognized arguments: customers}'
```

windows cmd doesn't like the space, but the usual trick of wrapping it in quotes gives this error

```
DBT>dbt run-operation generate_model_yaml --args "'{"model_name": "customers"}'"
Running with dbt=0.19.0

Encountered an error while running operation: Compilation Error
  The --vars argument must be a YAML dictionary, but was of type 'str'

```

is there a way to get this working on windows?

**Comment by jaypeedevlin** [comment]
I know this is months later, but I would try removing the space before `"customers"` to see if that fixes it

**Comment by scottcrowe** [comment]
I'm seeing the same thing as @jakub-auger on version 0.19.1 using the standard Windows cmd. The base example of `dbt run-operation generate_model_yaml --args '{"model_name": "customers"}'` works in Powershell and bash prompts running on Windows.

`dbt run-operation generate_model_yaml --args '{"model_name":"customers"}'` gives:
```
Encountered an error while running operation: Compilation Error
  The --vars argument must be a YAML dictionary, but was of type 'str'
```

Changing around the single and double quotes (i.e. `dbt run-operation generate_model_yaml --args "{'model_name': 'customers'}"` works in the basic command prompt. 

So two work arounds for Windows users: 
* Use Powershell instead of default cmd
* Swap Single and Double Quotes around

**Comment by pkanter** [comment]
> So two work arounds for Windows users:
> 
> * Use Powershell instead of default cmd
> * Swap Single and Double Quotes around

Super helpful, thank you.

**Comment by dharitsura248** [comment]
I believe @jakub-auger you can close this bug.

**Comment by jakub-auger** [comment]
ok :)

**Comment by PhilimonNag** [comment]
dbt run-operation generate_model_yaml --args '{"model_names": ["customers"]}'

you can try this

**Comment by tma-ngochieutran** [comment]
In window, I think you should run with the command:
`dbt run-operation generate_model_yaml --args "{\"model_names\": [\"customers\"]}"`
