### ISSUE TITLE
generate_columns fails if no database provided for Databricks

### ISSUE THREAD

**Issue by tfayyaz** [dbt-labs/dbt-codegen#72]
### Describe the bug

If you run generate_source with generate_columns = True then the operation fails as database is not supported for Databricks.

### Steps to reproduce
If you run the following it fails:

```
dbt run-operation generate_source --args '{"schema_name": "default","table_pattern":"*","generate_columns":True}'
```

### Expected results

It should run for Databricks even without a database and you should see the following

```
sources:
  - name: default
    tables:
      - name: my_first_dbt_model
        columns:
          - name: id

      - name: my_second_dbt_model
        columns:
          - name: id
```

### Actual results

it returns the following error:

```
Encountered an error while running operation: Runtime Error
  Field "path" of type Path in DatabricksRelation has invalid value {'database': Undefined, 'schema': 'default', 'identifier': 'my_first_dbt_model'}
```

### Screenshots and log output
See above

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ x] other (specify:  databricks)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.1
  - latest:    1.1.1 - Up to date!

Plugins:
  - databricks: 1.1.0 - Up to date!
  - spark:      1.1.0 - Up to date!
```

**The operating system you're using:**
Mac OS

**The output of `python --version`:**
Python 3.8.10

### Additional context
I was able to fix this by adding the following to macros/generate_source.sql

```
{% if target.type == 'databricks' and target.database is not defined %}
{% set database_name = None %}
{% endif %}
```

### Are you interested in contributing the fix?
I would like to contribute to fix this but would need guidance on the best way to make database_name optional if the method above is not the best way?

**Comment by dharitsura248** [comment]
Hi @tfayyaz , I am not even able to use generate_sources. 

When I am doing the below on windows OS with Databricks. I get the below error. Do you know how you were able to overcome this?
 ```
dbt run-operation generate_source --args "schema_name: bronze" --target sandbox   
 22:12:27  Running with dbt=1.3.0
 22:12:35  Encountered an error while running operation: Runtime Error
   Runtime Error
     Catalog namespace is not supported.
```

**Comment by tfayyaz** [comment]
@dharitsura248 can you try the following by adding the table_pattern arg:

```
dbt run-operation generate_source --args '{"schema_name": "bronze","table_pattern":"*"}'  --target sandbox
```

**Comment by dharitsura248** [comment]
@tfayyaz, I believe that was because we didn't have a unity catalog defined. Did you face the below issue? I believe our tables are managed tables. 

![image](https://user-images.githubusercontent.com/65309500/197825451-dfcbb7c2-6a98-4380-befe-a7b9c896981d.png)

**Comment by golivo28** [comment]
@dharitsura248 hi!

I ran into the same issue with the `generate_source` macro and found a worked it around by leveraging the [dispatch](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch) feature:

* first, I added this to my `dbt_project.yml`:
   ```yaml
   dispatch:
     - macro_namespace: dbt_utils
       search_order: ['my_dbt_project', 'dbt_utils']
   ```
* then in the `macros` folder, I added 2 macros:
   ```sql
   -- get_tables_by_pattern.sql
   {% macro default__get_tables_by_pattern_sql(schema_pattern, table_pattern, exclude='', database=target.database) %}
    show tables in {{ schema_pattern }}
   {% endmacro %}
   ```

  ```sql
   -- get_relations_by_pattern.sql
   {% macro default__get_relations_by_pattern(schema_pattern, table_pattern, exclude='', database=target.database) %}

    {%- call statement('get_tables', fetch_result=True) %}

      {{ dbt_utils.get_tables_by_pattern_sql(schema_pattern, table_pattern, exclude, database) }}

    {%- endcall -%}

    {%- set table_list = load_result('get_tables') -%}

    {%- if table_list and table_list['table'] -%}
        {%- set tbl_relations = [] -%}
        {%- for row in table_list['table'] -%}

            {%- set tbl_relation = api.Relation.create(
                schema=row.database,
                identifier=row.tableName
            ) -%}

            {%- do tbl_relations.append(tbl_relation) -%}
            
        {%- endfor -%}

        {{ return(tbl_relations) }}
    {%- else -%}
        {{ return([]) }}
    {%- endif -%}

  {% endmacro %}
  ```
* Then I ran `dbt run-operation generate_source --args '{"schema_name":"some_schema", "include_descriptions":True, "generate_columns":True, "name":"some_name"}'` and it worked! 

The reasoning behind my approach to work this around was basically that at my client, they have the default `HIVE_METASTORE`, and therefore the `INFORMATION_SCHEMA` was not available for querying (or that's what I was told by the team). The `generate_source` macro depends on dbt_utils' `get_relations_by_pattern` and likewise, this one depends on `get_tables_by_pattern_sql`, the latter (by default) queried the `INFORMATION_SCHEMA` for the required info about the tables.

So I overrode the `get_tables_by_pattern_sql` to use this query:

```sql 
 SHOW TABLES IN my_schema_name
```
Then I overrode the `get_relations_by_pattern` macro to admit the only 2 fields that query returned, namely `database` and `tableName` as the [Relation](https://docs.getdbt.com/reference/dbt-classes#relation) attributes `schema` and `identifier` respectively, though I believe mapping the `tableName` to the `identifier` may have been enough, since the `generate_source` macro only gets the `identifier` from the Relation.

Hope it helps!!
